name: Build and Test Python Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to v4 for Node.js 20 compatibility
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5 for Node.js 20 compatibility
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r streamlit/requirements.txt

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run pytest
      run: pytest streamlit/test_utils_api.py



    
