name: Build and Test Python Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Utilisez une version stable d'Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Installer les dépendances nécessaires sans 'python3-distutils'
        sudo apt-get install -y libxml2-dev libxslt-dev
        # Installer python3-distutils via pip (si disponible) ou manuellement
        wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python3-distutils/python3-distutils_3.11.11-1_all.deb
        sudo dpkg -i python3-distutils_3.11.11-1_all.deb || true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run pytest
      run: pytest -W ignore tests/test_utils.py